[default]
out = "mortar"
oarg = [
    "-Ofast",
    "-std=c++17",
    '-DCOMMITHASH=\"\\\"`git rev-parse HEAD`\\\"\"'
]
l = [
    "pthread"
]
com = "g++"
exclude = ["include/doctest/parts/doctest\\.cpp"]

[_default]
inherits = "default"
oarg = [
    "-DDOCTEST_CONFIG_DISABLE"
]
 
[_debug]
inherits = "default"
oarg = [
    "-g",
    "-DDOCTEST_CONFIG_INCLUDE_TYPE_TRAITS",
    "-DDOCTEST_CONFIG_NO_UNPREFIXED_OPTIONS"
]
include = ["include/doctest/parts/doctest\\.cpp"]

[test]
type = "command"
target = "_debug"
command = "$EXECUTABLE -dt-e"

[test_success]
type = "command"
target = "_debug"
command = "$EXECUTABLE -dt-e -dt-s"

[debug_gdb]
type = "command"
target = "_debug"
command = "gdb $EXECUTABLE -ex run"

[debug]
type = "command"
target = "_debug"
command = "$EXECUTABLE"

[run]
type = "command"
target = "_default"
command = "$EXECUTABLE"

[[deps]]
url = "https://github.com/doctest/doctest"
cpath = "doctest"
ipath = "doctest"
exclude = ["doctest/extensions", "doctest/BUILD.bazel"]

[[deps]]
url = "https://github.com/muellan/clipp"
cpath = "include"
ipath = "clipp"