name: run-tests
on:
  push:
    branches:
      - master
    paths:
      - "**.py"
      - "**.yml"
      - "**.cpp"
      - "**.hpp"
      - "**.h"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: kurocha/setup-cpp@v1
      - run: sudo apt install libboost-all-dev
      - run: python3 .avalon/comp.py --tests
      - run: ./mortar --dt-exit --dt-no-intro  >> $GITHUB_STEP_SUMMARY