name: run-tests
on:
  push:
    branches:
      - master
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls
      - uses: kurocha/setup-cpp@v1
      - run: sudo apt install libboost-all-dev
  build:
    runs-on: ubuntu-latest
    steps:
      - run: python3 .avalon/comp.py
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - run: ./mortar --dt-success --dt-exit
